[package]
name = "vfsd"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
thiserror = "1"
base64 = "0.22"
nix = { version = "0.28", default-features = false, features = ["fs","process"] }
tempfile = "3"
